# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(679, 577)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("encryption_z.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 681, 531))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.savekey_btn = QtGui.QPushButton(self.tab)
        self.savekey_btn.setGeometry(QtCore.QRect(190, 100, 121, 27))
        self.savekey_btn.setObjectName(_fromUtf8("savekey_btn"))
        self.statuswin_rb = QtGui.QTextEdit(self.tab)
        self.statuswin_rb.setGeometry(QtCore.QRect(310, 360, 351, 121))
        self.statuswin_rb.setFrameShape(QtGui.QFrame.WinPanel)
        self.statuswin_rb.setReadOnly(True)
        self.statuswin_rb.setObjectName(_fromUtf8("statuswin_rb"))
        self.encryptit_btn = QtGui.QPushButton(self.tab)
        self.encryptit_btn.setGeometry(QtCore.QRect(10, 430, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.encryptit_btn.setFont(font)
        self.encryptit_btn.setDefault(False)
        self.encryptit_btn.setFlat(False)
        self.encryptit_btn.setObjectName(_fromUtf8("encryptit_btn"))
        self.fileselection_lbl = QtGui.QLabel(self.tab)
        self.fileselection_lbl.setGeometry(QtCore.QRect(10, 180, 161, 17))
        self.fileselection_lbl.setObjectName(_fromUtf8("fileselection_lbl"))
        self.step2_lbl = QtGui.QLabel(self.tab)
        self.step2_lbl.setGeometry(QtCore.QRect(10, 140, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.step2_lbl.setFont(font)
        self.step2_lbl.setObjectName(_fromUtf8("step2_lbl"))
        self.key_txt = QtGui.QTextEdit(self.tab)
        self.key_txt.setGeometry(QtCore.QRect(10, 60, 301, 31))
        font = QtGui.QFont()
        font.setKerning(True)
        self.key_txt.setFont(font)
        self.key_txt.setFrameShape(QtGui.QFrame.WinPanel)
        self.key_txt.setReadOnly(True)
        self.key_txt.setObjectName(_fromUtf8("key_txt"))
        self.genkey_btn = QtGui.QPushButton(self.tab)
        self.genkey_btn.setGeometry(QtCore.QRect(10, 100, 161, 27))
        self.genkey_btn.setObjectName(_fromUtf8("genkey_btn"))
        self.step1_lbl = QtGui.QLabel(self.tab)
        self.step1_lbl.setGeometry(QtCore.QRect(10, 0, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.step1_lbl.setFont(font)
        self.step1_lbl.setObjectName(_fromUtf8("step1_lbl"))
        self.delete_cb = QtGui.QCheckBox(self.tab)
        self.delete_cb.setGeometry(QtCore.QRect(190, 240, 131, 22))
        self.delete_cb.setChecked(False)
        self.delete_cb.setObjectName(_fromUtf8("delete_cb"))
        self.key_lbl = QtGui.QLabel(self.tab)
        self.key_lbl.setGeometry(QtCore.QRect(10, 40, 91, 17))
        self.key_lbl.setObjectName(_fromUtf8("key_lbl"))
        self.Step3_lbl = QtGui.QLabel(self.tab)
        self.Step3_lbl.setGeometry(QtCore.QRect(10, 290, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Step3_lbl.setFont(font)
        self.Step3_lbl.setObjectName(_fromUtf8("Step3_lbl"))
        self.fileloc_txt = QtGui.QTextEdit(self.tab)
        self.fileloc_txt.setGeometry(QtCore.QRect(10, 200, 301, 31))
        self.fileloc_txt.setFrameShape(QtGui.QFrame.WinPanel)
        self.fileloc_txt.setReadOnly(True)
        self.fileloc_txt.setObjectName(_fromUtf8("fileloc_txt"))
        self.selectfile_btn = QtGui.QPushButton(self.tab)
        self.selectfile_btn.setGeometry(QtCore.QRect(10, 240, 161, 27))
        self.selectfile_btn.setObjectName(_fromUtf8("selectfile_btn"))
        self.encryption_logo = QtGui.QLabel(self.tab)
        self.encryption_logo.setGeometry(QtCore.QRect(340, 10, 311, 301))
        self.encryption_logo.setText(_fromUtf8(""))
        self.encryption_logo.setPixmap(QtGui.QPixmap(_fromUtf8("encryption_z.png")))
        self.encryption_logo.setScaledContents(False)
        self.encryption_logo.setObjectName(_fromUtf8("encryption_logo"))
        self.Status_lbl = QtGui.QLabel(self.tab)
        self.Status_lbl.setGeometry(QtCore.QRect(310, 340, 68, 17))
        self.Status_lbl.setObjectName(_fromUtf8("Status_lbl"))
        self.outputname_lbl = QtGui.QLabel(self.tab)
        self.outputname_lbl.setGeometry(QtCore.QRect(10, 320, 281, 17))
        self.outputname_lbl.setObjectName(_fromUtf8("outputname_lbl"))
        self.outputname_txt = QtGui.QLineEdit(self.tab)
        self.outputname_txt.setGeometry(QtCore.QRect(10, 340, 271, 29))
        self.outputname_txt.setObjectName(_fromUtf8("outputname_txt"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.D_step1_lbl = QtGui.QLabel(self.tab_2)
        self.D_step1_lbl.setGeometry(QtCore.QRect(10, 10, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.D_step1_lbl.setFont(font)
        self.D_step1_lbl.setObjectName(_fromUtf8("D_step1_lbl"))
        self.encryption_logo_2 = QtGui.QLabel(self.tab_2)
        self.encryption_logo_2.setGeometry(QtCore.QRect(350, 0, 311, 301))
        self.encryption_logo_2.setText(_fromUtf8(""))
        self.encryption_logo_2.setPixmap(QtGui.QPixmap(_fromUtf8("encryption_z.png")))
        self.encryption_logo_2.setScaledContents(False)
        self.encryption_logo_2.setObjectName(_fromUtf8("encryption_logo_2"))
        self.Dstep1desc_lbl = QtGui.QLabel(self.tab_2)
        self.Dstep1desc_lbl.setGeometry(QtCore.QRect(10, 40, 221, 21))
        self.Dstep1desc_lbl.setObjectName(_fromUtf8("Dstep1desc_lbl"))
        self.importkeyfile_txt = QtGui.QTextEdit(self.tab_2)
        self.importkeyfile_txt.setGeometry(QtCore.QRect(10, 60, 301, 31))
        font = QtGui.QFont()
        font.setKerning(True)
        self.importkeyfile_txt.setFont(font)
        self.importkeyfile_txt.setFrameShape(QtGui.QFrame.WinPanel)
        self.importkeyfile_txt.setReadOnly(True)
        self.importkeyfile_txt.setObjectName(_fromUtf8("importkeyfile_txt"))
        self.importkey_btn = QtGui.QPushButton(self.tab_2)
        self.importkey_btn.setGeometry(QtCore.QRect(10, 100, 131, 27))
        self.importkey_btn.setObjectName(_fromUtf8("importkey_btn"))
        self.D_step2_lbl = QtGui.QLabel(self.tab_2)
        self.D_step2_lbl.setGeometry(QtCore.QRect(10, 140, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.D_step2_lbl.setFont(font)
        self.D_step2_lbl.setObjectName(_fromUtf8("D_step2_lbl"))
        self.Dstep2desc_lbl = QtGui.QLabel(self.tab_2)
        self.Dstep2desc_lbl.setGeometry(QtCore.QRect(10, 170, 221, 21))
        self.Dstep2desc_lbl.setObjectName(_fromUtf8("Dstep2desc_lbl"))
        self.importencfile_btn = QtGui.QPushButton(self.tab_2)
        self.importencfile_btn.setGeometry(QtCore.QRect(10, 230, 111, 27))
        self.importencfile_btn.setObjectName(_fromUtf8("importencfile_btn"))
        self.encryptedFile_txt = QtGui.QTextEdit(self.tab_2)
        self.encryptedFile_txt.setGeometry(QtCore.QRect(10, 190, 301, 31))
        font = QtGui.QFont()
        font.setKerning(True)
        self.encryptedFile_txt.setFont(font)
        self.encryptedFile_txt.setFrameShape(QtGui.QFrame.WinPanel)
        self.encryptedFile_txt.setReadOnly(True)
        self.encryptedFile_txt.setObjectName(_fromUtf8("encryptedFile_txt"))
        self.delenc_cb = QtGui.QCheckBox(self.tab_2)
        self.delenc_cb.setGeometry(QtCore.QRect(140, 230, 181, 22))
        self.delenc_cb.setObjectName(_fromUtf8("delenc_cb"))
        self.D_step3_lbl = QtGui.QLabel(self.tab_2)
        self.D_step3_lbl.setGeometry(QtCore.QRect(10, 290, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.D_step3_lbl.setFont(font)
        self.D_step3_lbl.setObjectName(_fromUtf8("D_step3_lbl"))
        self.doutput_txt = QtGui.QLineEdit(self.tab_2)
        self.doutput_txt.setGeometry(QtCore.QRect(10, 340, 251, 29))
        self.doutput_txt.setObjectName(_fromUtf8("doutput_txt"))
        self.Dstep3desc_lbl = QtGui.QLabel(self.tab_2)
        self.Dstep3desc_lbl.setGeometry(QtCore.QRect(10, 320, 271, 21))
        self.Dstep3desc_lbl.setObjectName(_fromUtf8("Dstep3desc_lbl"))
        self.dstatus_lbl = QtGui.QLabel(self.tab_2)
        self.dstatus_lbl.setGeometry(QtCore.QRect(310, 330, 68, 17))
        self.dstatus_lbl.setObjectName(_fromUtf8("dstatus_lbl"))
        self.dstatuswin_rb = QtGui.QTextEdit(self.tab_2)
        self.dstatuswin_rb.setGeometry(QtCore.QRect(310, 350, 351, 121))
        self.dstatuswin_rb.setFrameShape(QtGui.QFrame.WinPanel)
        self.dstatuswin_rb.setReadOnly(True)
        self.dstatuswin_rb.setObjectName(_fromUtf8("dstatuswin_rb"))
        self.decryptit_btn = QtGui.QPushButton(self.tab_2)
        self.decryptit_btn.setGeometry(QtCore.QRect(10, 420, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.decryptit_btn.setFont(font)
        self.decryptit_btn.setDefault(False)
        self.decryptit_btn.setFlat(False)
        self.decryptit_btn.setObjectName(_fromUtf8("decryptit_btn"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 679, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Cryptonite", None))
        self.savekey_btn.setText(_translate("MainWindow", "Save Key FIle", None))
        self.encryptit_btn.setText(_translate("MainWindow", "Encrypt", None))
        self.fileselection_lbl.setText(_translate("MainWindow", "Select File to Encrypt", None))
        self.step2_lbl.setText(_translate("MainWindow", "Step 2:", None))
        self.genkey_btn.setText(_translate("MainWindow", "Generate Random Key", None))
        self.step1_lbl.setText(_translate("MainWindow", "Step 1:", None))
        self.delete_cb.setText(_translate("MainWindow", "delete original", None))
        self.key_lbl.setText(_translate("MainWindow", "Random Key", None))
        self.Step3_lbl.setText(_translate("MainWindow", "Step 3:", None))
        self.selectfile_btn.setText(_translate("MainWindow", "Select file to encrypt", None))
        self.Status_lbl.setText(_translate("MainWindow", "Status:", None))
        self.outputname_lbl.setText(_translate("MainWindow", "Choose output file name  (ex. myfile.enc) ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Encrypt", None))
        self.D_step1_lbl.setText(_translate("MainWindow", "Step 1:", None))
        self.Dstep1desc_lbl.setText(_translate("MainWindow", "Import key file", None))
        self.importkey_btn.setText(_translate("MainWindow", "Import Key File", None))
        self.D_step2_lbl.setText(_translate("MainWindow", "Step 2:", None))
        self.Dstep2desc_lbl.setText(_translate("MainWindow", "Import encrypted File ", None))
        self.importencfile_btn.setText(_translate("MainWindow", "Import file", None))
        self.delenc_cb.setText(_translate("MainWindow", "Delete Encrypted File", None))
        self.D_step3_lbl.setText(_translate("MainWindow", "Step 3:", None))
        self.Dstep3desc_lbl.setText(_translate("MainWindow", "Output file Name: ( original file name)", None))
        self.dstatus_lbl.setText(_translate("MainWindow", "Status:", None))
        self.decryptit_btn.setText(_translate("MainWindow", "Decrypt ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Decrypt", None))

